### ISSUE TITLE
Windows环境下，浏览器请求过程中后台报java.nio.file.InvalidPathException: Illegal char 错误

### ISSUE THREAD

**Issue by yuchaozhou** [ysc/QuestionAnsweringSystem#5]
Windows环境下，请求过程中报java.nio.file.InvalidPathException: Illegal char 错误。

具体错误日志：

20:36:11,926 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
20:36:11,926 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [logfile] to Logger[ROOT]
20:36:11,929 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [stdout] to Logger[ROOT]

开始构造问答系统
模型：models/chineseFactored.ser.gz
Loading parser from serialized file models/chineseFactored.ser.gz ... done [17.6 sec].
模式文件目录：/E:/Java/IDE/sts-bundle/vfabric-tc-server-developer-2.9.6.RELEASE/base-instance/wtpwebapps/deep-qa-web/WEB-INF/classes/questionTypePatterns/
模式匹配策略启用文件：QuestionTypePatternsLevel1_true.txt
模式匹配策略启用文件：QuestionTypePatternsLevel2_true.txt
模式匹配策略启用文件：QuestionTypePatternsLevel3_true.txt
	模式文件：QuestionTypePatternsLevel1_true.txt
	是否允许多匹配：true
	模式文件：QuestionTypePatternsLevel2_true.txt
	是否允许多匹配：true
	模式文件：QuestionTypePatternsLevel3_true.txt
	是否允许多匹配：true
问答系统构造完成
Question：谁是资深Nutch搜索引擎专家？ 搜索到Evidence 8 条
将Question：谁是资深Nutch搜索引擎专家？ 加入MySQL数据库
使用【模式匹配】的方法判断问题类型： 谁是资深Nutch搜索引擎专家？
问题：谁是资深Nutch搜索引擎专家？
四月 28, 2015 8:36:34 下午 org.apache.catalina.core.StandardWrapperValve invoke
严重: Servlet.service() for servlet [jsp] in context with path [/deep-qa-web] threw exception [javax.servlet.ServletException: java.lang.ExceptionInInitializerError] with root cause
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /E:/Java/IDE/sts-bundle/vfabric-tc-server-developer-2.9.6.RELEASE/base-instance/wtpwebapps/deep-qa-web/WEB-INF/classes/web/dic/word_v_1_3/word.local.conf
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at org.apdplat.qa.parser.WordParser.<clinit>(WordParser.java:48)
	at org.apdplat.qa.questiontypeanalysis.patternbased.PatternBasedMultiLevelQuestionClassifier.extractQuestionPatternFromQuestion(PatternBasedMultiLevelQuestionClassifier.java:301)
	at org.apdplat.qa.questiontypeanalysis.patternbased.PatternBasedMultiLevelQuestionClassifier.classify(PatternBasedMultiLevelQuestionClassifier.java:126)
	at org.apdplat.qa.system.QuestionAnsweringSystemImpl.answerQuestions(QuestionAnsweringSystemImpl.java:182)
	at org.apdplat.qa.system.QuestionAnsweringSystemImpl.answerQuestion(QuestionAnsweringSystemImpl.java:174)
	at org.apdplat.qa.system.QuestionAnsweringSystemImpl.answerQuestion(QuestionAnsweringSystemImpl.java:158)
	at org.apache.jsp.index_jsp._jspService(index_jsp.java:84)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by yuchaozhou** [comment]
错误已解决，详见：https://github.com/ysc/QuestionAnsweringSystem/pull/6
